import mongoose from 'mongoose';

const OrderSchema = new mongoose.Schema({
  "Sale Order Item Code": String,
  "Display Order Code": Number,
  "Reverse Pickup Code": String,
  "Reverse Pickup Created Date": String,
  "Notification Email": String,
  "Notification Mobile": String,
  "Require Customization": Boolean,
  "COD": Number,
  "Shipping Address Id": Number,
  "Category": String,
  "Invoice Code": String,
  "Invoice Created": Date,
  "Shipping Address Name": String,
  "Shipping Address Line 1": String,
  "Shipping Address Line 2": String,
  "Shipping Address City": String,
  "Shipping Address State": String,
  "Shipping Address Country": String,
  "Shipping Address Pincode": Number,
  "Shipping Address Phone": String,
  "Billing Address Id": Number,
  "Billing Address Name": String,
  "Billing Address Line 1": String,
  "Billing Address Line 2": String,
  "Billing Address City": String,
  "Billing Address State": String,
  "Billing Address Country": String,
  "Billing Address Pincode": Number,
  "Billing Address Phone": String,
  "Shipping Method": String,
  "Item SKU Code": String,
  "Channel Product Id": String,
  "Item Type Name": String,
  "Item Type Size": String,
  "Item Type Brand": String,
  "Channel Name": String,
  "SKU Require Customization": Boolean,
  "Gift Wrap": Boolean,
  "Gift Message": String,
  "HSN Code": Number,
  "MRP": Number,
  "Total Price": Number,
  "Selling Price": Number,
  "Cost Price": Number,
  "Prepaid Amount": Number,
  "Subtotal": Number,
  "Discount": Number,
  "GST Tax Type Code": Number,
  "CGST": Number,
  "IGST": Number,
  "SGST": Number,
  "UTGST": Number,
  "CESS": Number,
  "CGST Rate": Number,
  "IGST Rate": Number,
  "SGST Rate": Number,
  "UTGST Rate": Number,
  "CESS Rate": Number,
  "TCS Amount": Number,
  "Voucher Code": String,
  "Shipping Charges": Number,
  "Shipping Method Charges": Number,
  "COD Service Charges": Number,
  "Gift Wrap Charges": Number,
  "Packet Number": Number,
  "Order Date as dd/mm/yyyy hh:MM:ss": String,
  "Sale Order Code": String,
  "On Hold": Boolean,
  "Sale Order Status": String,
  "Priority": Number,
  "Currency": String,
  "Currency Conversion Rate": Number,
  "Sale Order Item Status": String,
  "Shipping provider": String,
  "Shipping Courier": String,
  "Shipping Arranged By": String,
  "Shipping Package Code": String,
  "Shipping Package Creation Date": Date,
  "Shipping Package Status Code": String,
  "Shipping Package Type": String,
  "Length(mm)": Number,
  "Width(mm)": Number,
  "Height(mm)": Number,
  "Tracking Number": String,
  "Dispatch Date": Date,
  "Facility": String,
  "Created": Date,
  "Updated": Date,
  "Weight": Number,
  "GSTIN": String,
  "Fulfillment TAT": Date,
  "Adjustment In Selling Price": Number,
  "Adjustment In Discount": Number,
  "Store Credit": Number,
  "SKU Name": String,
  "Seller SKU Code": String,
  "Channel Shipping": Boolean
}, { collection: 'All' });

const Order = mongoose.model('Order', OrderSchema);

export default Order;
